server:
  port: 8081

spring:
  # application
  application:
    name: ms-score
    title: Score Service - Enterprise Edition
    version: v1.0
    formatted-version: ‚òïÔ∏é Version 1.0 - to building 
    author: ·ù∞üñã Alejandro Fuentes | github ale-fuentes-ar

# datasource
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true
    username: sa
    password: rooT123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html