server:
  port: 8082

spring:
  # application
  application:
    name: ms-score
    title: Score Service - Enterprise Edition
    version: v1.0
    formatted-version: ‚òïÔ∏é Version 1.0 - to building 
    author: ·ù∞üñã Alejandro Fuentes | github ale-fuentes-ar

# VM configuration
  threads:
    virtual:
      enabled: true


# datasource
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true
    username: sa
    password: rooT123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  slq:
    init:
      mode: always

# Configuraci√≥n personalizada para llamar al MS-Score
services:
  ms-score:
    url: "http://localhost:8081"

resilience4j:
  circuitbreaker:
    instances:
      scoreService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs